import nextEslintPluginNext from "@next/eslint-plugin-next"
import nx from "@nx/eslint-plugin"
import baseConfig from "../../eslint.config.mjs"

export default [
    { plugins: { "@next/next": nextEslintPluginNext } },
    ...nx.configs["flat/react-typescript"],
    ...baseConfig,
    {
        ignores: [
            ".next/**/*",
            "**/out-tsc",
            // Generated by Next on every build and explicitly not editable, so
            // it cannot be held to the workspace style rules.
            "next-env.d.ts"
        ]
    }
]
